### ISSUE TITLE
Error to open the deployed application 

### ISSUE THREAD

**Issue by may215** [gokmen/electron-catalyst#1]
Hi, I tried to create deployment app for this application: https://github.com/andriyko/browser-dispatcher, and it does reduce the size of the application by 60% but, I can't open the application on my mac (El Capitan 10.11.6), I always get an error that said this application can not be opened because some computability issues. 

Any Ideas?

**Comment by gokmen** [comment]
Hi, 
We've developed this in one day 2 years ago and I haven't used it since that day, it's probably the issue with the pre-compiled catalyst binary in the repo, where you may need to re-compile it from https://github.com/cenkalti/catalyst Even though I'm not sure if Electron still uses the same directory structure.
